// moved from src/reportSummary.ts
export interface SystemStats {
  cpu: string | number;
  memoryUsedGB: string | number;
  memoryTotalGB: string | number;
  diskUsedGB: string | number;
  diskTotalGB: string | number;
  netRxMBps: string | number;
  netTxMBps: string | number;
}

export function generateSummary(stats: SystemStats, loadScore: string): string {
  const loadNum = parseFloat(loadScore);
  const memoryPercent = ((parseFloat(stats.memoryUsedGB as string) / parseFloat(stats.memoryTotalGB as string)) * 100).toFixed(1);
  const diskPercent = ((parseFloat(stats.diskUsedGB as string) / parseFloat(stats.diskTotalGB as string)) * 100).toFixed(1);
  
  let healthStatus = "";
  let healthEmoji = "";
  
  if (loadNum > 80) {
    healthStatus = "**Critical 🔥**";
    healthEmoji = "🚨";
  } else if (loadNum > 65) {
    healthStatus = "**High Load ⚡**";
    healthEmoji = "⚠️";
  } else if (loadNum > 40) {
    healthStatus = "**Moderate Load ⚙️**";
    healthEmoji = "📊";
  } else {
    healthStatus = "**Healthy ✅**";
    healthEmoji = "💚";
  }

  return `# ${healthEmoji} System Health Report

**Generated:** ${new Date().toLocaleString()}  
**Load Score:** **${loadScore}%** - ${healthStatus}

## 📊 Current Metrics

| Component | Usage | Status |
|-----------|-------|--------|
| **CPU** | ${stats.cpu}% | ${parseFloat(stats.cpu as string) > 80 ? '🔴 High' : parseFloat(stats.cpu as string) > 50 ? '🟡 Moderate' : '🟢 Normal'} |
| **Memory** | ${stats.memoryUsedGB}/${stats.memoryTotalGB} GB (${memoryPercent}%) | ${parseFloat(memoryPercent) > 85 ? '🔴 High' : parseFloat(memoryPercent) > 70 ? '🟡 Moderate' : '🟢 Normal'} |
| **Disk** | ${stats.diskUsedGB}/${stats.diskTotalGB} GB (${diskPercent}%) | ${parseFloat(diskPercent) > 90 ? '🔴 Full' : parseFloat(diskPercent) > 75 ? '🟡 Getting Full' : '🟢 Available'} |
| **Network** | ↓${stats.netRxMBps} / ↑${stats.netTxMBps} MBps | ${parseFloat(stats.netRxMBps as string) + parseFloat(stats.netTxMBps as string) > 10 ? '🔴 High' : '🟢 Normal'} |

## 🎯 System Analysis

${loadNum > 80 ? 
  "⚠️ **Action Required:** System is under heavy load. Consider scaling resources or optimizing workloads." : 
  loadNum > 65 ? 
  "📊 **Monitor Closely:** System load is elevated. Watch for resource bottlenecks." : 
  loadNum > 40 ? 
  "✅ **Normal Operation:** System performing within acceptable parameters." : 
  "💚 **Excellent:** System running optimally with plenty of headroom."
}

---
*Report generated by TrafficJS Real-time Monitor*
`;
}

export function generateShortSummary(stats: SystemStats, loadScore: string): string {
  return `🧠 Load: ${loadScore}% | 🖥️ CPU: ${stats.cpu}% | 💾 Mem: ${stats.memoryUsedGB}GB | 🌐 Net: ${stats.netRxMBps}/${stats.netTxMBps} MBps`;
}